site_name: RepChain Dashboard

markdown_extensions:
     - admonition
     - pymdownx.details
     - pymdownx.superfences
     - toc:
          permalink: "#"
          slugify: !!python/name:pymdownx.slugs.uslugify

plugins:
  - search:
  - with-pdf:
      author: RepChain DEV Team 
      toc_title: 目录
      toc_level: 3
      cover_title: RepChain Dashboard V2
      cover_subtitle: 使用说明
      # debug_html: true

theme:
  name: material
  language: zh
  highlightjs: true
  features:
      - search.highlight
      - navigation.top
  favicon: images/favicon.ico
  logo: images/favicon.ico
  palette:
      - scheme: default
        primary: green 
        toggle:
            icon: material/weather-night
            name: Switch to dark mode
      - scheme: slate
        primary: red
        toggle:
            icon: material/weather-sunny
            name: Switch to light mode

copyright: Copyright &copy; 2023 RepChain DEV Team

extra:
  version: 
    provider: mike

extra_css:
  - css/pdf-print.css

nav:
  - index.md
  